// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
/*import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4RDeOjOLDNA7IhG7JW9nVt8AcBB2k1U8',
    appId: '1:1029684554708:web:49e20463ac399eae2f0441',
    messagingSenderId: '1029684554708',
    projectId: 'slavia-app',
    authDomain: 'slavia-app.firebaseapp.com',
    storageBucket: 'slavia-app.appspot.com',
    measurementId: 'G-MHDCY987FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHjrGTi-8_F0_UD0fJ2dh03AmdT3H_kRc',
    appId: '1:1029684554708:android:d92a347fcda811492f0441',
    messagingSenderId: '1029684554708',
    projectId: 'slavia-app',
    storageBucket: 'slavia-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACQuzp_AAu33v5nxFHv-_Z7DlkSaXBLsQ',
    appId: '1:1029684554708:ios:79395d1d6c8321712f0441',
    messagingSenderId: '1029684554708',
    projectId: 'slavia-app',
    storageBucket: 'slavia-app.appspot.com',
    iosClientId: '1029684554708-i9nnr646qamk49921ol3iqk6qo3kfnds.apps.googleusercontent.com',
    iosBundleId: 'com.example.slaviaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACQuzp_AAu33v5nxFHv-_Z7DlkSaXBLsQ',
    appId: '1:1029684554708:ios:79395d1d6c8321712f0441',
    messagingSenderId: '1029684554708',
    projectId: 'slavia-app',
    storageBucket: 'slavia-app.appspot.com',
    iosClientId: '1029684554708-i9nnr646qamk49921ol3iqk6qo3kfnds.apps.googleusercontent.com',
    iosBundleId: 'com.example.slaviaApp',
  );
}*/
